### Environment variables
@host = http://localhost:3010
@apiBase = {{host}}
@token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsImVtYWlsIjoidGVzdC51c2VyQGV4YW1wbGUuY29tIiwicm9sZXMiOlsic3R1ZGVudCJdLCJpYXQiOjE3NjIyNzExNTUsImV4cCI6MTc2MjI3MjA1NX0.J7zQMdl8s4k6RSyHY59yCXrhOtR2gFNKml-ccrBev8M"
@refreshToken = "WcphTnWNTiRvbhelzUKAD_xUYCa3nAXVqhj7847Y9jTMfZjD-AiulUDlOEC8RqIJ"

### POST /auth/login (PUBLIC)
POST {{apiBase}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "test.user@example.com",
  "password": "StrongP@ssw0rd"
}

### POST /auth/login (ADMIN)
POST {{apiBase}}/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin.user@example.com",
  "password": "AdminP@ss1"
}



### POST /auth/refresh (PUBLIC)
POST {{apiBase}}/auth/refresh
Accept: application/json
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### POST /auth/logout (PUBLIC)
POST {{apiBase}}/auth/logout
Accept: application/json
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

### GET /auth/me (PROTECTED)
GET {{apiBase}}/auth/me
Accept: application/json
Authorization: Bearer {{token}}

# Notes:
# - Use the login response to obtain accessToken/refreshToken.
# - For web flows consider storing the refreshToken in an httpOnly cookie.
