### Create user (admin only)
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "name": "New User",
  "email": "newuser@example.com",
  "password": "StrongP@ssw0rd!",
  "role": "teacher"
}

### List users (teacher or admin)
GET http://localhost:3000/users
Authorization: Bearer {{teacher_token}}


### Get self
GET http://localhost:3000/users/{{my_id}}
Authorization: Bearer {{student_token}}


### Get other user (should be 403 for non-admin)
GET http://localhost:3000/users/99999
Authorization: Bearer {{student_token}}
